name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Java Generics Tests
      id: java-generics-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Java Generics Tests
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JAVA-GENERICS-TESTS_RESULTS: "${{steps.java-generics-tests.outputs.result}}"
      with:
        runners: java-generics-tests
